//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokeShopVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSMasterCat
    {
        public int MasterCatID { get; set; }
        public string MasterCatName { get; set; }
        public string SubCat { get; set; }
    }
}
