//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokeShopVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWYWnamegender
    {
        public int NameID { get; set; }
        public string NameValue { get; set; }
        public string Gender { get; set; }
    }
}
