//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokeShopVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWYWwishlist
    {
        public int WishListID { get; set; }
        public int MemberID { get; set; }
        public string WLName { get; set; }
    }
}
